# Generated by Django 5.2.4 on 2025-07-29 04:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Diary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diary_number', models.CharField(max_length=20, unique=True)),
                ('part_type', models.CharField(choices=[('A', 'Part A'), ('B', 'Part B')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='GridFlipLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flip_number', models.PositiveIntegerField()),
                ('flipped_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('part_a', models.CharField(max_length=255)),
                ('part_b', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('diary_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_diary_1', to='game.diary')),
                ('diary_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_diary_2', to='game.diary')),
                ('quote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.quote')),
            ],
        ),
        migrations.AddField(
            model_name='diary',
            name='quote',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.quote'),
        ),
    ]
