# Generated by Django 5.2.4 on 2025-07-29 13:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diary_id', models.CharField(max_length=100, unique=True)),
                ('quote_part', models.CharField(choices=[('A', 'A'), ('B', 'B')], max_length=1)),
                ('has_registered', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('quote_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.quote')),
            ],
        ),
    ]
