# Generated by Django 5.2.4 on 2025-07-29 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_player'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='quote_instance',
            new_name='quote',
        ),
        migrations.AlterField(
            model_name='player',
            name='diary_id',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='has_registered',
            field=models.BooleanField(default=False),
        ),
    ]
