# Generated by Django 5.2.4 on 2025-07-29 15:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_rename_quote_instance_player_quote_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='player',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='player',
            name='diary_id',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AddField(
            model_name='player',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='game.group'),
        ),
    ]
