# Generated by Django 5.2.4 on 2025-07-29 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_group_remove_player_created_at_alter_player_diary_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gridfliplog',
            name='is_status',
            field=models.BooleanField(default=False),
        ),
    ]
