# Generated by Django 5.2.4 on 2025-07-29 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_gridfliplog_is_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='points',
            field=models.IntegerField(default=0),
        ),
    ]
