# Generated by Django 5.2.4 on 2025-07-30 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_group_points'),
    ]

    operations = [
        migrations.CreateModel(
            name='FrontendQuotePair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diary_number', models.CharField(max_length=20)),
                ('quote_id', models.IntegerField()),
                ('is_verified', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'your_frontend_table_name',
                'managed': False,
            },
        ),
        migrations.RemoveField(
            model_name='gridfliplog',
            name='flipped_at',
        ),
    ]
