# Generated by Django 5.2.4 on 2025-07-30 16:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_frontendquotepair_remove_gridfliplog_flipped_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='gridfliplog',
            name='player1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='flip_player1', to='game.player'),
        ),
        migrations.AddField(
            model_name='gridfliplog',
            name='player2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='flip_player2', to='game.player'),
        ),
    ]
