# Generated by Django 5.2.4 on 2025-07-30 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0008_gridfliplog_player1_gridfliplog_player2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gridfliplog',
            name='flip_number',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='gridfliplog',
            name='player1',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='gridfliplog',
            name='player2',
            field=models.CharField(max_length=50),
        ),
    ]
